root: true

env:
  es6: true
  node: true

plugins:
  - import
  - node
  - promise
  - standard

rules:
  intent:
    - 2
    - spaces
  quotes:
    - 2
    - single
  comma-dangle:
    - 2
    - never
  operator-linebreak:
    - 2
    - after
