language: node_js
node_js:
  - '7.7'

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules

# before_script: 'snyk auth $SNYK_TOKEN'
script: 'yarn test'
