#!/usr/bin/env sh
#
# bootstrap installs things.

cd "$(dirname "$0")/.."

set -e

if [ -f .env ]; then
  source .env
fi

echo "installing dependencies..."
npm install

echo "setting up heroku..."
heroku config:set INTEGRATION_ID="${INTEGRATION_ID}" WEBHOOK_SECRET="${WEBHOOK_SECRET}" PRIVATE_KEY="$(cat pdfify.pem)" --app "${HEROKU_APP_NAME}"
